Repository OSUGameDev/LocalWar, pull requests merged in 2019-11, with the labels that each got.

#23 Networking Bug Fixes and Main Menu Level Selection
  Local War/Assets/Editor.meta
  Local War/Assets/Editor/LevelSelectMenu.cs
  Local War/Assets/Editor/LevelSelectMenu.cs.meta
  Local War/Assets/Editor/Levels.xml
  Local War/Assets/Editor/Levels.xml.meta
  Local War/Assets/Editor/PostBuildServerCreator.cs
  Local War/Assets/Editor/PostBuildServerCreator.cs.meta
  Local War/Assets/Resources/Prefab/UI/MainMenuCanvas.prefab
  Local War/Assets/Resources/Script/Character/MovementSys.cs
  Local War/Assets/Resources/Script/System/NetworkFakeGame.cs
  Local War/Assets/Resources/Script/UI/Level.cs
  Local War/Assets/Resources/Script/UI/Level.cs.meta
  Local War/Assets/Resources/Script/UI/MainMenu.cs
  Local War/Assets/Scene/MainMenu.unity
Labels: bug, features

#29 Feature pooled game objects
  Local War/Assets/Resources/Script/System/PGOManager.cs
  Local War/Assets/Resources/Script/System/PGOManager.cs.meta
  Local War/Assets/Resources/Script/Test.meta
  Local War/Assets/Resources/Script/Test/PGOTester.cs
  Local War/Assets/Resources/Script/Test/PGOTester.cs.meta
  Local War/Assets/Resources/Script/Test/RemoveObjTimer.cs
  Local War/Assets/Resources/Script/Test/RemoveObjTimer.cs.meta
  Local War/Assets/Scene/PGOTest.unity
  Local War/Assets/Scene/PGOTest.unity.meta
Labels: enhancement

#30 Character Systems - Sound System
  Local War/Assets/Resources/Art/Sounds.meta
  Local War/Assets/Resources/Art/Sounds/Explosion_SFX.wav
  Local War/Assets/Resources/Art/Sounds/Explosion_SFX.wav.meta
  Local War/Assets/Resources/Art/Sounds/Laser_SFX.wav
  Local War/Assets/Resources/Art/Sounds/Laser_SFX.wav.meta
  Local War/Assets/Resources/Script/Character/WeaponSys.cs
  Local War/Assets/Resources/Script/System/SoundSys.cs
  Local War/Assets/Resources/Script/System/SoundSys.cs.meta
  Local War/Assets/Resources/Script/Weapon/Weapon.cs
Labels: features
